name: skeletons
description: A Flutter package for building custom skeleton widgets to mimic the page's layout while loading.
version: 1.0.0
homepage: https://github.com/badjio/skeletons/

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
